### ISSUE TITLE
different result when running RJson::pack (solved)

### ISSUE THREAD

**Issue by JRTian** [dmitrirussu/RJSON-php#3]
I have a issue when running RJson::pack.
I did not dig into it deeply  but I changed the source code a little bit and solved the issue finally.

issue:
I have a specific array to be packed.(I am not sure if the issue is related to the specific array)
If I run RJson::pack to pack an specific array twice, the first time I can get the result as I 
expect but the second time I got the result totally different.
The issue will lead to that RJson::pack will return unexpect result when pack arrays in a same 
process.
 
solution:
//reset the static variables everytime when running RJson::pack
public static function pack($data, $returnJsonEncode = false) {
	  static::$schemas = array();
	    static::$maxSchemaIndex = 0;
	    static::$decodedSchemas = array();
	    static::$maxDecodedSchemaIndex = 0;
		if (!$returnJsonEncode) {
			return self::encode($data);
		}
		return json_encode(self::encode($data));
	}

**Comment by dmitrirussu** [comment]
Thanks, I did a commit for that problem.
